apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: code-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /exercises/v1/exercises/*
        backend:
          serviceName: code-exercises
          servicePort: 8080
      - path: /inputs/v1/inputs/*
        backend:
          serviceName: code-inputs
          servicePort: 8080
      - path: /scripts/v1/script/*
        backend:
          serviceName: code-ide
          servicePort: 8080
