apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: code-complete
spec:
  rules:
  - http:
      paths:
      - path: /exercises/*
        backend:
          serviceName: code-exercises
          servicePort: 8080
      - path: /inputs/*
        backend:
          serviceName: code-inputs
          servicePort: 8080
      - path: /outputs/*
        backend:
          serviceName: code-outputs
          servicePort: 8080
      - path: /subjects/*
        backend:
          serviceName: code-subjects
          servicePort: 8080
      - path: /scripts/*
        backend:
          serviceName: code-ide
          servicePort: 8080
