apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: code-complete
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /exercises/v1/exercises/.*
        backend:
          serviceName: code-exercises
          servicePort: 8080
      - path: /outputs/v1/outputs/.*
        backend:
          serviceName: code-outputs
          servicePort: 8080
      - path: /subjects/v1/subjects/.*
        backend:
          serviceName: code-subjects
          servicePort: 8080
      - path: /scripts/v1/scripts/.*
        backend:
          serviceName: code-ide
          servicePort: 8080
